### ISSUE TITLE
GitHub Classroom bug: empty repos

### ISSUE THREAD

**Issue by danwallach** [education/classroom#1148]
Related public post: https://education.github.community/t/possible-bug-with-github-classroom-clones-with-no-content/17274/4

I emailed the exact repos (which have student names, so can't go here in public) to education@github.com

Three students ended up with completely empty repos, so I just pushed the content into them directly and everything was fine. A fourth student ended up with a README.md and nothing else. I did a "push --force" to that repo and everything was fine thereafter.

**Comment by mozzadrella** [comment]
Thanks for reporting this @danwallach.

**Comment by gchallen** [comment]
I'd like to reopen this issue, since I'm seeing the same problem. (Hi Dan!) With 600 students in my class, a few empty repos becomes a huge pain to fix.

**Comment by gchallen** [comment]
Happy to provide more information if it is helpful. We're using an invitation link. Some small but non-zero percent of the time accepting the invitation produces an empty repository. With 600 students I've had maybe one or two of these per-assignment.

The problem is that there is no way for the student to rectify this problem. They can't accept the invitation again, unless they create a new account, which shouldn't be required and causes other confusion. I have to go in manually, find their repository, and then delete it, at which point they can try again.

It seems like this is a bug with Classroom somewhere. A workaround would be to allow students to accept the invitation again if the existing repository is empty.

**Comment by danwallach** [comment]
My own workaround, hinted at above, is to have my master repo on my laptop. "git add remote" for the student's repo, then "git push --force" to the student's repo. This is slightly preferable, but I really would appreciate this bug being addressed.

**Comment by tarebyte** [comment]
@danwallach @gchallen it's rather difficult on our end to know because the importer is not part of classroom.

That being said I wonder if we have a force recreation mechanism that would let you do it through the UI?

**Comment by gchallen** [comment]
The "solution" is to just delete the repository and let the student try again. However, this requires manual work on my part. I don't want to use the UI—I just want a way for this to work every time 🙂 .

**Comment by danwallach** [comment]
UX on a "force recreation" mechanism could be confusing. We don't want students accidentally blowing away the repo with all their work by pressing the wrong button.

(I had a student deliberately nuke their .git directory and a bunch of their files, reinitialize everything, do a force-push to their repo of whatever was left, and only then realize they'd done something really unfortunate. Thankfully I was able to find commit IDs from their Travis-CI history and those old commits hadn't yet been garbage collected yet. Never doubt that a student will find a way to do something ... deeply unfortunate.)

**Comment by tarebyte** [comment]
@danwallach I was thinking this would be on the teacher's side rather than on the student side.

We could also add a step on to the end of the process where if there is a designated template that we make sure that the two repos look the same or that it has content, and if not automatically blow it away and try it again.

**Comment by gchallen** [comment]
@tarebyte: your second suggestion is much more along the lines of what I'm after. At minimum you can remove empty repos and start again. (I haven't seen the partial clone problem that @danwallach  reported.)

**Comment by LINKIWI** [comment]
Potentially some additional insight. I have not had time to inspect the source to identify a root cause.

Here are some reproduction steps:

1. Create a starter code repository `A`. Push an initial commit.
2. Create an assignment. Set the starter code repo for the assignment to `A`.
3. Rewrite the initial commit of `A` (`git commit --amend && git push origin HEAD --force`)
4. Create a repo from the public assignment link using an account that does not have permission to read or write to `A`. The account displays a `500 Internal Server Error` when trying to create the repo.
5. Notice that the repo is empty.

My suspicion is that the assignment saves the starter code repository based on a unique identifier that is somehow affected by the initial commit. Rewriting this initial commit breaks the saved association of the assignment to the starter code repository. The assignment creation logic defaults to creating an empty repo if the import fails, causing the observed behavior.

cc @tarebyte

**Comment by mfagan451** [comment]
Let me also chime in here with our Rice experience. We have posted 11 assignments so far. For every assignment, between 5 and 10 students have empty repos. It appears to be completely stochastic.
It is different students every time, and it seems to occur at random times during the day.

**Comment by eblanton** [comment]
I have 140 students in a course, and I have had one instance of these in each of two projects.  As some of the previous posters, I'd be happy to provide more information (and specific repositories) to GitHub Education if it would help.

**Comment by eblanton** [comment]
As an update, regarding the above "blow it away and try again" solution ... For my students who have had this problem, the repository has been truly empty, so I have been able to simply pull their repo, pull the handout code, then push back to their repo without problem.  As @gchallen said, this is too manual to be a long-term solution for large classes, but it suggests that the "fix" may be to simply check for an empty repo after creation and force-push if necessary.  (That is, assuming no fix forthcoming from GitHub on their side.)

**Comment by gchallen** [comment]
Just a bump since this is still happening to me, and seems worse with our latest assignment. This assignment is a bit larger than the previous ones, so I'm wondering if that offers a clue about what the underlying issue is.

**Comment by markpolyak** [comment]
I have the same issue here as well. Currently I have a course with a single assignment and about 40 students already accepted the invite link and tried to import the repository. Today a 4th student had issues with importing the repo when it turned out to be empty. So in my case 10% of students get stuck because of GitHub Classroom assignment import malfunctioning during the last 3 weeks.

The solution I'm using is to delete the empty repositories so the student can accept the assignment one more time.

**Comment by gchallen** [comment]
Yes, this is a well-known problem and biting a bunch of us that are using Classroom.

I may break down and write a small cron-type script to just find empty repos matching a pattern and delete them. Unfortunately due to (AFAICT unfounded) FERPA fears we don't have a strong linkage between repository and student identity—students eventually commit an email.txt file containing their student ID. So it may not be possible to contact them when this happens, which would normally be useful.

**Comment by Kadaaran** [comment]
Hi there 👋 

I've been trying to reproduce this issue on my side so I can write a fix. 
Unfortunately I still can't ...
I'm trying to find another way by trying different things on the setup.

@gchallen do you have an exemple of an empty repo to give me so I try to check the status ?

**Comment by Kadaaran** [comment]
Hi @mfagan451 @markpolyak @eblanton I'm actually digging into it do you have the name of the assignment (and student login) who had empty repos so I can take a look ?

**Comment by markpolyak** [comment]
Hi @Kadaaran 

Please, note that the following repositories are private, but I can manually make them public if it will help you in any way.

1. This is the repository we had problems with a few days ago on March 14th: https://github.com/k43guap/os-task1-ALLZsaz
I deleted empty repository and the same student was able to successfully import it on a second attempt. So it is not empty now. Strange thing is that I first saw this repository on TravisCI as a new untracked repository, but I couldn't find it in a list of organization's repositories on GitHub. When I tried to open the repository from a direct link on TravisCI I saw a frozen import progress bar. Waited for a few minutes to confirm that the progress bar doesn't move at all and then closed the browser tab. Some time after an empty repository appeared under organization's account on GitHub. There was also an email from GitHub saying "Import to k43guap/os-task1-ALLZsaz failed", which I can forward to you if it will help. I don't remember receiving such emails with other cases of empty repositories.

2. This one did not import correctly on February 26th: https://github.com/k43guap/os-task1-AnastasiaVasileva8
Student described it that the import progress bar did not move for about 15 minutes and when it finally finished the repository was empty.
Again empty repository was deleted and a second import attempt on that day was successful.

3. One more problematic repository on February 26th was https://github.com/k43guap/os-task1-Sonnad
After empty repository was removed second import attempt went flawless.

4. Can't remember who was the fourth student with an empty repository. It looks like I just saw that a new repository was created with zero commits and deleted it right away, before the student contacted me about an error.

**Comment by Kadaaran** [comment]
Hi @markpolyak 👋 
I see 🤔Thank you for all the informations ! 

In order to write a fix I need to check the import status of an empty repo. If you encounter again an empty repository could you tell me so I can quickly check what happened ?

Thank you !

**Comment by gchallen** [comment]
Thanks @Kadaaran! I'll let you know the next time this happens. Usually students complain quickly and I fix the problem quickly. But I may see if I can get my large course staff to stress test things a bit, since they won't care if the clone doesn't work.

**Comment by Kadaaran** [comment]
Hi @gchallen 👋 
I'm actually on a fix, I don't know how long it will take but I'm doing my best 💪

**Comment by gchallen** [comment]
Glad to hear it @Kadaaran! In the mean time, here's an example of broken repository creation: https://github.com/cs125-illinois-students/MP5-chenminni1113. FWIW I will need to fix this by mid-day, so if you can't look at it by then it will be gone. Sorry for the fast turnaround, but my students have an assignment due today.

**Comment by Kadaaran** [comment]
Hi @gchallen thank you I was able to check ! 🙌

**Comment by gchallen** [comment]
OK great! @Kadaaran: can I clear these now? (Just had another one. Ugh.)

**Comment by eblanton** [comment]
Interestingly, I haven't had an empty repo come up since that request, and I released a new project last week.  I'm glad progress is being made.

**Comment by gchallen** [comment]
@Kadaaran: is Ethan's report good luck or were changes made?

**Comment by Kadaaran** [comment]
@gchallen Good luck sorry 🙇 I'll let you know as soon as the PR is made.

**Comment by eblanton** [comment]
While it may be good luck, it continues.  I've had a couple hundred clones (I'm not sure how many, but somewhere between 200 and 300) since the last student complaint.

**Comment by markpolyak** [comment]
The issue of empty repos didn't show up for a couple of months, but today one of my students got it again. The empty repository is https://github.com/k43guap/os-task4-Sonnad
I transfered this empty repo to be public (it is private by default) and will keep it for a day. After that I will have to delete it so that student can try to import it again and continue with the task.

I also received an email from GitHub with the following text:

> Hi markpolyak!
> 
> The import to https://github.com/k43guap/os-task4-Sonnad failed. More information may be available at <https://github.com/k43guap/os-task4-Sonnad/import>.
> 
> If you have an questions, please contact us at https://github.com/contact.
> 
> --
> Your friends at GitHub

**Comment by markpolyak** [comment]
Interestingly, this is the same student that already had a problem with an empty repository in February. It may be a coincidence though, because he didn't have problems importing task2 & task3. Empty repos were with task1 and task4.

But after some more thought

**Comment by gchallen** [comment]
I do think that student behavior can cause this problem. The screen that Classroom throws up when it's working on the initial clone is a bit confusing in the sense that it seems like it wants to update when it's done but doesn't always. I suspect that sometimes this leads students to hit cancel which somehow can cause this problem.

Given that there's been little movement from GH on this issue, and I have a few more cycles now, I may plan a Classroom Empty Repo Killer as a small summer project. The idea would be: subscribe to new repository webhooks, detect empty repositories, automatically delete them and contact the student to have them accept the invitation again. Would anyone else find that useful?

**Comment by eblanton** [comment]
@gchallen if you're going to go that far, I think you can just flat fix the problem by pushing the source to the empty repository.  I've been fixing failed clones (manually) by simply pushing from my local handout repo.

**Comment by gchallen** [comment]
Good point—that would also work.

**Comment by danwallach** [comment]
Or one step farther, create all the hundreds of clones at once and just email your students.

**Comment by joelwross** [comment]
I've hit this same issue still (though not as frequently as in the past); maybe ~5 times out of 8*150 assignment accepts. My solution is to force-push the starter code to the individual empty repo (takes 10 seconds once the student lets us know the week).

```
cd path/to/starter-code
git push -f https://github.com/org/assignment-student master
```

I don't know what student behavior is causing the problem, though it seems like a check for an empty repo after accepting the assignment should catch the use cas?

**Comment by d12** [comment]
Hey! Template repositories for starter code launched a couple of months ago and should fix this issue. Since this has been inactive for over a year, I'm going to close it out. https://classroom.github.com/help/using-template-repos-for-assignments
