### ISSUE TITLE
Students repo does not show up in their Github profil

### ISSUE THREAD

**Issue by kaspersoerensen** [education/classroom#1260]
Hi,

I have a Github Classroom with one assignment. The students have signed up and accepted the assignment.

For some students however, the cloned repository from the assignment does not show up in their overview of repositories, when they log in to Github. They are able to access the repo through the link provided in the mail they got when accepting the repo.

**Comment by Kadaaran** [comment]
Hi @kaspersoerensen ,

> the cloned repository from the assignment does not show up in their overview of repositories
Do you mean in their profile page or the GitHub homepage ?

When students clone assignments repositories, they are not "owners" of these repos. They have access to the repo in your Organization that's why it's not showing in their profile page `repositories` section. 
They can find their link in the GitHub homepage on the right in the `repositories` section.

Can you keep me updated if they are able to find them ? 🙏 

Thanks a lot !

**Comment by kaspersoerensen** [comment]
Hi @Kadaaran 

Thank you so much for the fast answer. I will have the next lecture on friday, so by then I will know more - and try and find out more. But I think you are right. When thee go to the GitHub Homepage they should be able to see the repo there. 

This issue can be closed for now 😃
