### ISSUE TITLE
Request for private repositories using wrong organization

### ISSUE THREAD

**Issue by MarkCLewis** [education/classroom#1497]
_issue_

##
#### What you were trying to do ?
_In the request for private repositories for a classroom it automatically made the request for my personal organization (@MarkCLewis) instead of for the course (@CSCI1321-F18 and @CSCI3395-F18). The page for the request doesn't appear to have an option to select anything else._

#### What happened (include screenshot if you can) ?
_I got an email saying I have free repositories and the request page shows two accepted requests, but they are listed as being for @MarkCLewis and not the organization associated with the course._

#### Step-by-step reproduction instructions
Go to New Assignment > Individual Assignments. Then click on the link for requesting private repositories (https://education.github.com/discount_requests/new). It is defaulting to the wrong organization and I can't change it.

I will note that this has never happened to me in previous semesters.

**Comment by BenEmdon** [comment]
Hey @MarkCLewis, it looks like your issue is about [`education.github.com`](https://education.github.com) instead of [`classroom.github.com`](https://classroom.github.com) (this project).

For education support please alert the support team on https://github.com/contact. 
Sorry for the inconvenience.

I'll close this issue, but feel free to open another if you have any problems with [`classroom.github.com`](https://classroom.github.com).
