### ISSUE TITLE
Invalid form redirects to bad url

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#155]
Minor stuff, but worth noting:

If you leave the form at `/organizations/new` blank and submit, it redirects you to `/organizations` instead of `/organizations/new`. If you dismiss the flash, the layout is a bit messed up.

**Comment by tarebyte** [comment]
@johndbritton the form is still valid, and if you fix the error you can still submit it. But if you redirect instead of re-rendering then you lose the flash message errors.

Do you have any suggestions about how to sustain the errors?

I opened up #156, and right now it just has the flash message fix

**Comment by johndbritton** [comment]
If you navigate to `/organizations` directly you get a not found, maybe that's because there's a route for `POST` but not `GET`. Never really noticed this behavior before, but maybe it's expected. Feel free to ignore.
