### ISSUE TITLE
Successful invitations can be reaccepted

### ISSUE THREAD

**Issue by edmundmok** [education/classroom#1586]
**Describe the bug**
Invitations that have already been accepted before can be reaccepted through the same link, causing a duplicate repository to be created. Possibly related to #1462.

**Expected behavior**
Only one repository should be created the first time the invitation is accepted.

**Comment by BenEmdon** [comment]
Thanks for writing in, I’ll investigate when I get some time 👀

**Comment by jtppragg** [comment]
I also have this issue. During my first experience using GitHub Classroom most of my students ended up working with a duplicated repository (name ended with a number, ej. xxx-2) because of clicking the link several times, and GitHub Classroom only shows me the first repository (name not ended with -2, ej. xxx) so I cannot track their work from the assistant.

**Comment by inigobou** [comment]
+1
