### ISSUE TITLE
importing starter project stuck

### ISSUE THREAD

**Issue by Rogue899** [education/classroom#1616]
i have followed a url link to github classroom page to import a project the importer is stuck on witing for hours

**Comment by BenEmdon** [comment]
Hey @Rogue899 👋 
Could you please provide more info about the problem by filling out all the sections in the bug report at https://github.com/education/classroom/issues/new?template=bug_report.md
Please include screenshots and links. 

Closing this due to lack of information. Please open a new issue with more details.
