### ISSUE TITLE
Classroom Assistant - Could not find assignment

### ISSUE THREAD

**Issue by manu-msr** [education/classroom#1632]
**Describe the bug**
Classroom assitant couldn't find my assigment and I don't know why.

**Screenshots**
![image](https://user-images.githubusercontent.com/15841718/46551183-aeecad80-c89c-11e8-8fa1-fc28684987f4.png)

**Comment by srinjoym** [comment]
Hi @manu-msr 👋

Thanks for writing in, Sorry you're hitting this issue! Our recommended flow for using Classroom Assistant is to click the <kbd>Download Repositories</kbd> button from your assignment page.

Let me know if that works for you, if not I can go through some more debugging steps with you!

**Comment by manu-msr** [comment]
Hi @srinjoym ✋ 

I tried but it didn't work.

Thank you!

**Comment by srinjoym** [comment]
@manu-msr I've been investigating your issue and it looks like we are hitting an error on our end when trying to load assignments on Classroom Assistant for your account. Not sure what the source of the issue is yet, I'll keep debugging and let you know when I have an update.

Thanks for your patience 🙌

**Comment by A-Alaa** [comment]
The same issue happens to me also. E.g this assignment: https://classroom.github.com/classrooms/35454503-sbme-tasks/assignments/sbe206a-assignment-1

By the way, the avatar doesn't show on the classroom assistant (not sure if they are related bugs).

**Comment by sfrewen** [comment]
Same issue as A-Alaa. "Could not find assignment" even when clicking the "Download Repositories" button from GitHub Classroom, and wrong avatar at the top right of the window. When clicked, the avatar only displays the "Sign out" option (not sure if there should be anything else).

**Comment by srinjoym** [comment]
@manu-msr Sorry for the delay on this, finally figured out the issue on the Classroom Side and pushed up a fix with #1673. This should fix the issue for you, let me know if you have any other problems!

@A-Alaa and @sfrewen I'm not sure if you were hitting the same bug as @manu-msr, let me know if this issue is fixed for you. If not, we can open up a new issue and go through some debugging steps.

**Comment by rkumar-teaching** [comment]
I faced the same issues today But then clicking on the "Download Repositories" using classroom assistant button from GitHub Classroom worked!

**Comment by agricolamz** [comment]
I faced the same issues with two my classes:

https://classroom.github.com/classrooms/56619293-2019_2020_ds4dh/assignments/ds4dh-hw1
https://classroom.github.com/classrooms/56619293-2019_2020_ds4dh/assignments/ds4dh-hw2

Links are from clicking `Download repositories` button.

It happened yesterday, but two-three weeks ago I downloaded and evaluated first of this classes.

BUT: when I reloged in to the GitHub assistant using **mail address** and not just **login** it successfully recognized  me (showed my avatar at the right corner) and get the access to assignments. So I'd stipulate that this is a problem of logging in.
