### ISSUE TITLE
Better error reporting on Assignment Creation flow

### ISSUE THREAD

**Issue by BenEmdon** [education/classroom#1684]
It was difficult to determine the cause of #1575 because the error was obscured by the following non descriptive error strings:

https://github.com/education/classroom/blob/49864b3246ccc4d48829ddb6276a7bf98ebb2253/app/models/assignment_repo/creator.rb#L5-L8

Instead we should use errors straight from GitHub like we did (before moving it to the creator pattern) `GroupAssignmentRepo`s:
https://github.com/education/classroom/blob/49864b3246ccc4d48829ddb6276a7bf98ebb2253/app/jobs/group_assignment_repo/create_github_repository_job.rb#L41-L42

- [x] Make errors better for `AssignmentRepo`
- [ ] Make errors better for `GroupAssignmentRepo`

**Comment by BenEmdon** [comment]
Is this actually closed by #1892? 
CC @shaunakpp you have the context to agree/disagree since you were working on the refactor with `GroupAssignmentRepos`.

**Comment by shaunakpp** [comment]
@BenEmdon @EricPickup #1892 doesn't entirely close this issue as we still have to remove the error constants from the code, but it can be done only when #1884 gets merged. So let us keep this issue open till we do that. What do y'all think?

**Comment by EricPickup** [comment]
I see - currently `GroupAssignmentRepos` already report the detailed github error (as seen [here](https://github.com/education/classroom/blob/master/app/jobs/group_assignment_repo/create_github_repository_job.rb#L47)) but #1884 brings error constants to it which is understandable since that's what we're doing in the individual assignment creator. In that case I'll have to do the same thing to `GroupAssignmentRepos` once #1884 is merged, as @shaunakpp mentioned. I'll keep the issue open!

**Comment by BenEmdon** [comment]
@EricPickup in that case could you change the wording in your pr?
```diff
- Closes #1684.
+ Part of #1684.
```

Otherwise, it will merge and close this PR
