### ISSUE TITLE
Unable to create classroom for long-named organization

### ISSUE THREAD

**Issue by dowobeha** [education/classroom#1723]
**Describe the bug**
Create an organization with a long name, such as 2019-Spring-UIUC-LING490-LS4 

**To Reproduce**
1. Go to https://classroom.github.com/classrooms/new
2. Click on the organization

**Expected behavior**
A classroom should be created

**Screenshots**
![screen shot 2018-12-22 at 2 03 48 pm](https://user-images.githubusercontent.com/331829/50378213-6d91b180-05f2-11e9-8423-6579909d19b2.png)

**Comment by AhmedKamal20** [comment]
This is not a bug, it's the expected behavior

https://github.com/education/classroom/blob/6d3fa4663268345a264a0e77e031eb0da81471ca/app/models/organization.rb#L24

i don't know why though.

**Comment by BenEmdon** [comment]
Classroom creates an organization using an organization's name if it is present, otherwise it uses the organizations handle (referred to as `login` in the GitHub API):
https://github.com/education/classroom/blob/1fbb76487f5a201076ac0b778071cd519b2e6d13/app/models/organization/creator.rb#L160

@dowobeha I looked up your organization with the handle `"019-Spring-UIUC-LING490-LS4"` at it's organization profile page (https://github.com/2019-Spring-UIUC-LING490-LS4) and I saw that your organization has the name `"LING 490 - Spring 2019 - University of Illinois - Section LS4"`.

Running a quick length check on this name yielded:
```rb
"LING 490 - Spring 2019 - University of Illinois - Section LS4".size
# => 61
```

So this isn't a bug since your organization's name is longer than 60 characters. 

To change your organizations display name go to https://github.com/organizations/2019-Spring-UIUC-LING490-LS4/settings/profile
