### ISSUE TITLE
Student repositories inflate contribution count on profile

### ISSUE THREAD

**Issue by nsilvestri** [education/classroom#1745]
**Describe the bug**
Cloning the assignment for the students also affects the count of contributions on my profile, as the commit I made on the starter repository got cloned to ~100 students and the commits got duplicated per student repository. I now have 300+ contributions that I did not make on January 10th and 17th.

**To Reproduce**
1. Create a new assignment, with an existing repository as starter code.
2. Accept the assignment from multiple accounts.
3. See GitHub contribution count change.

**Expected behavior**
Contributions should only count towards the original repository.

**Additional context**
This is probably an issue with the contribution counting system, as I've had a similar issue when duplicating a repository. Not sure if this is in the scope of GitHub Classroom. But it is annoying to have 300+ contributions counting on my profile, when it should be 3. I just like accurate statistics.

**Comment by BenEmdon** [comment]
@nsilvestri you are right that this is a problem with the contribution counting system. 

If you use https://github.com/new/import to duplicate a repo on GitHub, then the contributions will be counted however many times you duplicate the repo.

Classroom uses the source import API underneath and is also subject to this problem.

Unfortunately this problem is out of scope for Classroom to fix, but I suggest you contact GitHub support (https://github.com/contact) to make them aware of the problem.
