### ISSUE TITLE
Assignment fails: "We were not able to add you to the Assignment as a collaborator, please try again."

### ISSUE THREAD

**Issue by ericpollmann** [education/classroom#1761]
**Describe the bug**
Assignment fails: "We were not able to add you to the Assignment as a collaborator, please try again."
Creating repository Errored
Importing starter code: Errored

**To Reproduce**
1. https://classroom.github.com/assignment-invitations/985d6b58f7ee6caffbce5871c696bb45/setup
2. Accept assignment
3. 2 of 8 people have experienced this error.

**Expected behavior**
Assignment is created, repo is cloned.

**Screenshots**
![screen shot 2019-02-05 at 12 32 01 pm](https://user-images.githubusercontent.com/7079390/52307809-7941f900-2950-11e9-92d0-31a483127e76.png)

**Additional context**
N/A

**Comment by ericpollmann** [comment]
No official comment on https://github.com/education/classroom/issues/1271, but it may be due to 2FA being required for our org, I'll check with the student.

**Comment by ericpollmann** [comment]
Verified we do not have 2FA required for our org, but the students still had repeated failures accepting the assignment.
<img width="705" alt="screen shot 2019-02-05 at 2 21 58 pm" src="https://user-images.githubusercontent.com/7079390/52308143-7562a680-2951-11e9-884a-33dffd0bfa4e.png">

**Comment by BenEmdon** [comment]
@ericpollmann I have just checked your organization and looks like your organization (https://github.com/clearbrain) is on the "team" plan and only has 12 seats. This means that only 12 users can be added to the organization. You can confirm this by going to https://github.com/organizations/clearbrain/settings/billing.

To fix the problem you can either upgrade your plan to have more seats, or if you are an education organization you can apply for the education discount at https://education.github.com/discount.

Since this issue can only be fixed on your end I am going to close this issue for now.

**Comment by leoxtc** [comment]
Hello I have the full plan and some of my studants are having this issue. 

My organization Display name is Kapital Trading

What I can do to check this ?

**Comment by BenEmdon** [comment]
@leoxtc I just checked your plan and it appears that all of your organization seats are filled. (Same as the issue being experienced above). You can confirm this by going to https://github.com/organizations/clearbrain/settings/billing.

To fix the problem you can either upgrade your plan to have more seats, or if you are an education organization you can apply for the education discount at https://education.github.com/discount.
