### ISSUE TITLE
Cannot clone assignment with GitHub Actions acitvated

### ISSUE THREAD

**Issue by maciossek** [education/classroom#1767]
**Describe the bug**
It's not possible to clone the assignment (accept it) and my guess is that this is related to GitHub Actions. I'd like to switch from travis-ci to GitHub actions.

**To Reproduce**
1. Go to https://classroom.github.com/a/aJPpPaAF
2. See error

**Expected behavior**
Cloning works e.g. with this assignment: https://classroom.github.com/a/crZTyKsH

**Comment by srinjoym** [comment]
Hi @maciossek,

Thanks for writing in! 

This issue is related to https://github.com/education/classroom/issues/1728. OAuth apps like GitHub Classroom are not allowed to modify the `main.workflow` file. We can't do anything on our side until that restriction changes. Let me know if you have any questions.
