### ISSUE TITLE
Starter code import hanging

### ISSUE THREAD

**Issue by divegeek** [education/classroom#1788]
When trying to import starter code for a new student repo, the import process hangs.

I see this has happened to others, recently, but the last message says to report again as the source of the problem may be different.

A project whose import is hung right now is: https://github.com/MorganHigh/connect-four-garbleflunk/import

**Comment by divegeek** [comment]
It did finally finish. I don't know how long it took.  When I looked this morning (10 hours after starting it) it was done.

**Comment by BenEmdon** [comment]
Glad to hear that it completed. Unfortunately the starter code import times are subject to GitHub's infrastructure constraints. If a long import happens again, it would be better to [contact GitHub support](https://github.com/contact) about the import, since they are better equipped to handle these issues.
