### ISSUE TITLE
Importing starter code freezes

### ISSUE THREAD

**Issue by MelathStofi** [education/classroom#1801]
Importing starter code doesn't want to finish while creating my assignment repository in @CodecoolGlobal classroom. As I've read it must be a webhook problem. I need help in this, either webhook fix or suggestions what I should do.

**Comment by srinjoym** [comment]
@MelathStofi This issue is being tracked here: https://github.com/education/classroom/issues/1778. This crops up most often when the GitHub Source Import API is under high load due to resource constraints. Let me know if you're still having this issue if so it might be a separate issue. Really sorry for the inconvenience.
