### ISSUE TITLE
After being approved for private repos, I get "have reached the limit of 0"

### ISSUE THREAD

**Issue by profgsindel** [education/classroom#1821]
**Describe the bug**
After being approved for private repos, I get "have reached the limit of 0"

**To Reproduce**
Create an assignment
Click "Private Repos"
Create...

Error: "have reached the limit of 0"

**Expected behavior**
Expected I could grant repos. Have 5 students 8 weeks, several assignments... 500 or so.

**Comment by mozzadrella** [comment]
Hi,

You were approved for an individual account, but you'll need to get a Team Plan Discount for Classroom.

You still need to apply separately for private repositories for any GitHub organization you are using for academic purposes:

https://education.github.com/discount_requests/new

After the approval is processed, verified faculty can now easily upgrade any GitHub organization being used for academic purposes to [GitHub Team](https://github.com/pricing) with a single click.

Simply visit your GitHub Education benefits page at https://education.github.com/benefits.

Organizations you own will be listed near the bottom of the page:

![screenshot 2019-03-06 at 12 13 06 pm](https://user-images.githubusercontent.com/6764844/53907148-cd043880-4009-11e9-8449-be66e15e13e1.png)

Click the **Upgrade** button next to the organization name to immediately upgrade it for free to GitHub Team.

Please note:

You may be required to re-verify your faculty status one time in order to unlock this new functionality. To do so, click "submit your information again" near the top of the page to reapply. It will take a few days for us to reverify you, so thank you in advance for your patience.
