### ISSUE TITLE
Initialize assignments without starter code with a README

### ISSUE THREAD

**Issue by tarebyte** [education/classroom#186]
@sivilotti brought up a great question:

>
One question that just occurred to me: will the repos that
are created for each group be initialized with a basic README?
In other words, will students be able to immediately clone the
GH repo to start working?

> (I ask because I'm not providing any starter code for these
assignments. In the past I've always created the assignment
repos with an initial basic README so that groups could start
by cloning the GH one.  I assume that's how the classroom
tool will work too?)

Right now we just create an empty repository if they don't have starter code. Is it too much to assume that the user would want a README for easy cloning?

/cc @johndbritton

**Comment by johndbritton** [comment]
Maybe a checkbox like on GitHub?

**Comment by sivilotti** [comment]
Yes, a checkbox would be great.  Selecting the "initialize with a README" checkbox should be mutually exclusive with providing starter code.

**Comment by johndbritton** [comment]
I've given this some more thought and I'm not fully convinced that this is a necessary feature. Rather than add another option to the setup process, folks who need a starter repository can use the starter code feature. It has the added benefit that the `README.md` is in their control and they can distribute instructions.

@tarebyte What are your thoughts on this? Why would we do this rather than just prompt the user for instructions to include in a README that we create. I don't think the default repository GitHub creates is very useful to students.

**Comment by sivilotti** [comment]
How about a radio button with 3 choices:
* include starter code from GitHub (+ textbox for repo to use)
* include only a default readme: repo will be immediately cloneable
* create empty repo: students will add an existing repo

Maybe it's not *really* adding a new option, since it's just replacing the optional text box? :-)

I don't think the third option is very helpful to students (or instructors) and it's the current default!  The first option is certainly useful, but does require a little extra work on the instructor's part every time an assignment is set up (for the first time), which would be nice to avoid...

**Comment by johndbritton** [comment]
I filed this as a feature request and will leave it open. We don't have a timeline to add this feature, but it's something we're going to consider in the future.

**Comment by johndbritton** [comment]
So we've taken to the pattern of labeling feature requests and closing them unless we have plans to work on them in the immediate term. That's not to say we aren't going to consider this, just keeping the issues list clean.
