### ISSUE TITLE
Image/gif won't load

### ISSUE THREAD

**Issue by BenEmdon** [education/classroom#1896]
**Describe the bug**
The image/gif on https://classroom.github.com/help/probot-settings and https://classroom.github.com/help/upgrade-your-organization won't load.

**To Reproduce**
Go to https://classroom.github.com/help/probot-settings or https://classroom.github.com/help/upgrade-your-organization

**Expected behavior**
Image/gif should load.

**Screenshots**
<img alt="Screen Shot 2019-06-25 at 11 17 40 AM" src="https://user-images.githubusercontent.com/11095731/60122810-db9e6900-973a-11e9-91ae-3ce950b18c80.png">

<img alt="Screen Shot 2019-06-25 at 11 20 11 AM" src="https://user-images.githubusercontent.com/11095731/60122969-35069800-973b-11e9-805e-c3765d83d059.png">

**Additional context**
Related to #1794

**Comment by EricPickup** [comment]
Looking into it. I'm 90% sure the issue is here: https://raw.githubusercontent.com/education/classroom/master/docs/probot-settings.md

We're using a raw HTML image tag to link to an image in the asset pipeline. We can't use the `image_tag` helper since this is a markdown file. I think the solution would be to move these gifs to the `/public` directory, where static assets belong. I'll create a PR!
