### ISSUE TITLE
Importing Starter code takes forever

### ISSUE THREAD

**Issue by TheRijn** [education/classroom#1938]
**Describe the bug**
importing starter code takes forever when accepting a assignment

**To Reproduce**
Accept an assignment, for example https://classroom.github.com/a/ntKY1Xry

**Expected behavior**
Get redirected to the repo 

**Screenshots**
Same as all the other, so no screenshot provided 

**Additional context**
Probably a probleem with the organisation web hooks?

**Comment by d12** [comment]
Hey @TheRijn ! Thanks for the report, sometimes the GitHub Importer gets overloaded and starter code imports take a long time. We're currently working on a solution which we're hoping to begin rolling out some time closer to the end of this month.

Please see @BenEmdon 's update here: https://github.com/education/classroom/issues/1591#issuecomment-501070754, engineering work for this project began recently. 

I'm going to close this issue so that we're tracking the problem in a single place. We'll update https://github.com/education/classroom/issues/1591 as progress is made.
