### ISSUE TITLE
Unable to add a starter code repository to a new assignment

### ISSUE THREAD

**Issue by aalgahmi** [education/classroom#1965]
**Describe the bug**
I'm trying to create a new assignment but not able to due to a problem with starter code repository. I keep getting the error message: 
**
> Starter code repository cannot be empty. Select a repository that is not empty or create the assignment without starter code.
**

The started code repository I selected shows on the  **Add your starter code from GitHub (optional)** auto-generated dropdown and I have verified again and again that it's not empty. I was able to do this without a problem last week. I even tried the same starter code repository that worked form last week, but that did not work either.

**To Reproduce**
1. Go to  Github Classroom, sign in, and click your organization
2. Click new assignment
3. Fill in the form and select a non-empty starter code repository
4. Submit the form

**Expected behavior**
I expect the assignment to be created given the starter code repository

**Comment by ericpickup-test1** [comment]
Hi @aalgahmi, thanks for reporting this. Preventing teachers from using empty repos in starter code was a fix put in last week. Sounds like something went wrong with it.

Would you be able to link me to the starter code repository if it's public?

**Comment by EricPickup** [comment]
Hi @aalgahmi, thanks for reporting this. Preventing teachers from using empty repos in starter code was a fix put in last week. Sounds like something went wrong with it.

Would you be able to link me to the starter code repository if it's public?

**Comment by aalgahmi** [comment]
Of course. It's  https://github.com/WSU-SUMMER-2019/web2620-assignment-07. Thanks

**Comment by EricPickup** [comment]
Thanks @aalgahmi. I tried it out with your repo and found that there is an edge case.

When checking if the repo is empty [we're calling the API to look at the repo's contributor statistics](https://github.com/education/classroom/blob/master/app/models/github_repository.rb#L152) and pulling the number of commits from that. However, it seems like your git name/email configuration is off and your commit history is not linked to a GitHub account. This does not count as a contribution and therefore the number of commits in your repo by contributors is zero.

![image](https://user-images.githubusercontent.com/1490434/60860211-9753a400-a1e3-11e9-8a45-5eacf366ce07.png)


I'll open an issue to fix this asap but I'm having trouble figuring out the best way to patch this so I expect it might take a couple days. In the mean time you can fix this by fixing your git configuration so that your commit history is linked to your GitHub account: https://help.github.com/en/articles/why-are-my-commits-linked-to-the-wrong-user

**Comment by aalgahmi** [comment]
Thank you! that fixed the issue for me.

**Comment by waqarsaleem** [comment]
I am facing the same issue. I believe the user information is correct. The repository with the starter code is at https://github.com/hu-cs-224-summer-19/hw03
