### ISSUE TITLE
Can't Push to Repository Cloned using Classroom

### ISSUE THREAD

**Issue by gcschmit** [education/classroom#2182]
**Describe the bug**

When student repositories are cloned using Classroom Assistant, I receive an error when trying to push any changes that I make to these repositories. This does not occur when I clone the repositories using GitHub Desktop or git in a terminal.

**To Reproduce**

1. In Classroom Assistant (1.0.5), specify the assignment, choose repositories, choose the destination, and click on the Archive button.
2. Make a change to one of the repositories.
3. Add (git add) and commit (git commit) the change.
4. Attempt to push the change (git push).
5. The following error is displayed:

> remote: Temporary clone tokens are read-only.
> fatal: unable to access 'https://x-access-token:[token omitted]@github.com/[path omitted].git/': The requested URL returned error: 403

6. If I set the remote (git remote set-url origin <path>), I can successfully push the change.

**Expected behavior**

I expected that the first push command would succeed.

**Additional context**

I have two factor authentication configured for my GitHub account.

**Comment by srinjoym** [comment]
👋 @gcschmit Thank you so much for writing in! Unfortunately, this is a known limitation of Classroom Assistant since we use a temporary token to clone the repository from GitHub (we decided to do this so that Classroom Assistant wouldn't have to be its own OAuth app).

The workaround right now is to either clone the assignment again (since the tokens would be refreshed) or manually replace the URL in the repositories to remove the temporary token. This process and the feature request, in general, are outlined in https://github.com/education/classroom-assistant/issues/103. I'm going to close this out, but feel free to ask any follow-up questions on the thread in Classroom Assistant :)
