### ISSUE TITLE
Ability to create a set of teams from existing organization's teams

### ISSUE THREAD

**Issue by faloi** [education/classroom#245]
Hi there! 

I'm part of a group that teaches in several universities in Argentina, and we have many organizations with a lot of teams created with a [tool we developed](https://github.com/dds-utn/enma), with the same spirit as this one: automating the creation of assignments. Obviously we will be deprecating that one in favour of GitHub Classroom but (as good programmers we are) we don't want to create all the teams again inside Classroom. 

Testing the tool a little, I've seen that teams created **within** Classroom can be reused, but that's not true for preexistent teams. Do you think a _"Create grouping from existing teams"_ feature could be available in the short term?

Keep up the good work!

**Comment by faloi** [comment]
I imagine something like this:

![image](https://cloud.githubusercontent.com/assets/1585835/10034601/584feb20-6168-11e5-9536-bb6eedeae50d.png)

**Comment by johndbritton** [comment]
@faloi Thanks for the feedback. It's not likely that we're going to add a feature to import existing teams into Classroom for GitHub, mainly because of the decisions we've made around how we use teams for access control in the application.

Right now, students are added to teams by selecting an existing team or creating a new team when they accept an invitation. If a teacher wants to assign teams, that will happen outside of the application for now. In the future we may consider ways for students to be given assigned teams through the application.

Classroom for GitHub is designed to be use with a dedicated organization from the beginning and for now we're trying to keep the feature set as simple as possible.

**Comment by faloi** [comment]
>  If a teacher wants to assign teams, that will happen outside of the application for now. 

Ok, let's say I do that. I still won't have a way to include them in an assignment, right?

**Comment by johndbritton** [comment]
> Ok, let's say I do that. I still won't have a way to include them in an assignment, right?

I don't really understand the question here. The case I was suggesting was that you split your class into teams of four and tell them verbally who their groups are (or they choose in class). Then, one student from each team accepts the assignment and creates a team using the invitation. The others join the team by choosing from the list.

**Comment by faloi** [comment]
I'll try it again with a concrete example.

We have a course (in fact many courses, but let's take just one to simplify things) with 15 groups of 2 students. Each of them has a team within [our organization](https://github.com/unq-objetos3-alumnos), we created them some months ago with the tool I mentioned in the description.

Next week we want to roll out a new assignment, and we want to try Classroom for that. But _ideally_ I don't want to tell each student to register their group again, because we already have that information.

**Comment by johndbritton** [comment]
Thanks for clarifying, I understand now.

> But ideally I don't want to tell each student to register their group again, because we already have that information.

Ideally you wouldn't have to make them join new teams, but due to the way we're managing them with the Classroom app, it's not really easy for us to import arbitrary team data from an existing organization.

@tarebyte Do you have any ideas for workarounds that wouldn't make things a lot more complex for the standard use case?

**Comment by arademaker** [comment]
+1 asking for a solution! I am running in the same case here. I am creating the second assignment and I would like to preserve the teams already formed by the students. I would like to be able to edit the previous created 'group of teams' if one or other team is created. My course is https://github.com/ED-2016/

**Comment by johndbritton** [comment]
> I am creating the second assignment and I would like to preserve the teams already formed by the students.

@arademaker If your first assignment was in Classroom then this should be possible for you already. Just choose the same "group of teams" when creating the assignment and students will only be prompted to choose if they didn't participate in the first assignment.

> I would like to be able to edit the previous created 'group of teams' if one or other team is created.

We don't have this ability yet, but it's something we're planning to implement. @dinever has laid the foundations of that interface in https://github.com/education/classroom/pull/511.

It's not currently possible to change the "group of teams" for an assignment after it's created, you can only set that when you first create it. As a workaround, you could delete assignment 2 and recreate it. When you make it again, be sure to choose the correct "group of teams."
