### ISSUE TITLE
Can't add students

### ISSUE THREAD

**Issue by timscherr88** [education/classroom#2525]
**Describe the bug**
I started to connect my GitHub Classroom to Canvas, but was uncertain if I had sufficient authority, so I hit back.   Now it says Github is connected to Canvas, even though I never completed the connection, and won't let me manually add students.   Only the add through Canvas option is available.   I am stuck.  Please allow manual entry of students to ALWAYS be an option.
**To Reproduce**

**Expected behavior**
Please allow manual entry of students to ALWAYS be an option.
**Screenshots**

**Additional context**

**Comment by d12** [comment]
:wave: @timscherr88 , we disallow manual roster changes while linked to an LMS because it breaks our sync functionality that keeps the GitHub roster in line with your LMS roster. If you're looking to just use manual rosters, you can un-link the LMS from your classroom and work from there. Let me know if I can help out :)

**Comment by timscherr88** [comment]
Nate,

The link to the LMS was made by another party, and when he unlinked it I was able to do the manual addition.

Best,

Tim

**Comment by d12** [comment]
Glad to hear!
