### ISSUE TITLE
Canvas Integration Configuration 404

### ISSUE THREAD

**Issue by lizfischer** [education/classroom#2528]
**Describe the bug**
When opening an assignment in Canvas set to open with GitHub Classroom, there is a 404 error. The link from the 404 page that says "Go back to classroom dashboard" results in "classroom.github.com refused to connect."

**To Reproduce**
1. Follow the [instructions ](https://classroom.github.com/help/setup-canvas)for setting up Canvas integration. (Note here: the language in the documentation does not match the current interfaces. Canvas calls the URL field "Launch URL" and the GitHub configuration calls it "Application Auto-Configuration URL")

2. Create a Canvas assignment with the Submission Type set to External Tool. Use Find to select GitHub Classroom. This error whether or not "Load This Tool In A New Tab" is selected.

3. Save the assignment.

4. Navigate to the assignment page.

**Expected behavior**
The assignment page displays a GitHub classroom page (I've never seen this working so I'm not sure what it should do, exactly), or (if Load This Tool In A New Tab was selected) the "Load in a new window" button does the same.

**Screenshots**
Integration setup
![image](https://user-images.githubusercontent.com/7800842/72687079-41c85000-3ac0-11ea-94d4-da9b4277ddf5.png)

Assignment settings
![image](https://user-images.githubusercontent.com/7800842/72687117-881daf00-3ac0-11ea-8a53-d41403aebbc6.png)

Assignment page
![image](https://user-images.githubusercontent.com/7800842/72687139-a97e9b00-3ac0-11ea-89d8-934bd1989cb7.png).

**Comment by lizfischer** [comment]
Apologies if I'm just missing something here...

**Comment by womenpower19111** [comment]
The fucWhy is it that GitHub is harassing me i have been trying and trying to inscribe from you services because i simply am not going to use GitHub for an thing in my position so het the fuck shit away from me i am feed up with it now what's its going take you sorry motherfuckers

Sent from Yahoo Mail on Android 
 
  On Sun, Jan 19, 2020, at 5:59 PM, Liz Fischer<notifications@github.com> wrote:   
Describe the bug
When opening an assignment in Canvas set to open with GitHub Classroom, there is a 404 error. The link from the 404 page that says "Go back to classroom dashboard" results in "classroom.github.com refused to connect."

To Reproduce
   
   -    
Follow the instructions for setting up Canvas integration. (Note here: the language in the documentation does not match the current interfaces. Canvas calls the URL field "Launch URL" and the GitHub configuration calls it "Application Auto-Configuration URL")

   -    
Create a Canvas assignment with the Submission Type set to External Tool. Use Find to select GitHub Classroom. This error whether or not "Load This Tool In A New Tab" is selected.

   -    
Save the assignment.

   -    
Navigate to the assignment page.


Expected behavior
The assignment page displays a GitHub classroom page (I've never seen this working so I'm not sure what it should do, exactly), or (if Load This Tool In A New Tab was selected) the "Load in a new window" button does the same.

Screenshots
Integration setup


Assignment settings


Assignment page
.

**Comment by lizfischer** [comment]
> The fucWhy is it that GitHub is harassing me i have been trying and trying to inscribe from you services because i simply am not going to use GitHub for an thing in my position so het the fuck shit away from me i am feed up with it now what's its going take you sorry motherfuckers Sent from Yahoo Mail on Android.

Hi @womenpower19111 -- you're probably watching this repository on GitHub... if you go to [this link  ](https://github.com/education/classroom) and there's a button near the top right that says "Unwatch" you can click it and change to "Not Watching" to stop notifications. 
![image](https://user-images.githubusercontent.com/7800842/72691657-b3b68e80-3aec-11ea-8889-834ff5aae9e2.png)

You can also go to https://github.com/settings/notifications and uncheck things there to stop notifications for everything.

**Comment by d12** [comment]
:wave: @lizfischer , right now the integration only supports roster imports which you'll find in the students tab of your Classroom. Until we build out that support, trying to embed Classroom in your assignments like this won't do anything super useful :)

**Comment by lizfischer** [comment]
Oh, that explains it! Thank you :)
