### ISSUE TITLE
Get overview of which students have and haven't submitted an assignment via pull request

### ISSUE THREAD

**Issue by tansaku** [education/classroom#335]
Is there a way to get an overview of which students have and haven't submitted an assignment via pull request using the classroom system?  And possibly even to get an overview of CI stats running on their pull requests?

Many thanks in advance

**Comment by johndbritton** [comment]
> Is there a way to get an overview of which students have and haven't submitted an assignment

If you go to the assignment page in Classroom for GitHub you can see a list of who has accepted the assignment and you can access the repositories from that page.

> via pull request using the classroom system?

Classroom for GitHub doesn't have any features for displaying pull requests or other repository activity in the app.

> And possibly even to get an overview of CI stats running on their pull requests?

We don't have any features for CI status in Classroom for GitHub, but I think this is something we could consider in the future.

One idea would be to allow setting the CI build system on the assignment so that builds are automatically run on every repository created by Classroom for GitHub.

Thanks for sharing your idea, I've labeled this as `feature-request` so we can easily find it in the future. We use feature requests like this to inform our future directions.

I'm closing this since it's not something that we can implement straight away, but feel free to add additional details we can use when we consider adding related features.
