### ISSUE TITLE
Repositories occasionally created with wrong user's name

### ISSUE THREAD

**Issue by bamford** [education/classroom#360]
I have had two cases where a user has clicked to join an assignment and a repo has been created correctly, but with the wrong username.

The is the link to the assignment page in case it helps you investigate:
https://classroom.github.com/classrooms/9050108-mpags-python-2015/assignments/coursework
and this is the corresponding organisation:
https://github.com/mpags-python

On the first occasion, although a student was logged in and clicked the invitation link, the repo was created with my (the assignment creator's) username.  I had previously joined my own assignment (to test the process) and then deleted the repo.  I'd seen some other discussion in the issues about odd behaviour when deleting repos, and that work was ongoing, so I didn't report it at the time.

However, I've just seen a second case, in which a student joined the assignment, but the repo that was created was named after a completely different user.  The erroneous user doesn't appear to be associated with the course at all. The correct user was assigned access to the repo (even though the names didn't match).

Both times I have simply renamed the repo to fix the problem, and haven't noticed any further issues.

Is there any way that the repo creation code could accidentally get the wrong username?

**Comment by tarebyte** [comment]
There shouldn't be, but I will look into it.

Thanks for the report @bamford!

**Comment by johndbritton** [comment]
Labeled as `report` until we can reproduce the issue.

**Comment by bpesquet** [comment]
Hi,

Same for me: regularly, the repos are created with my username instead of the student's. Today, it happened 4 times for an assignment given to 22 students. Here's the assignment link : https://classroom.github.com/classrooms/14162426-slam5/assignments/presidents

**Comment by MattForshaw** [comment]
Good morning,

This is also a serious issue for my assignment at https://classroom.github.com/classrooms/16018527-ncl-cloudcomputing/assignments/csc8110-cloud-computing-2015-16. Please feel free to interrogate the audit logs for my assignment if you feel this will be useful.

One user affected by this is 'sherylcoe' whose assignment was originally created ending '-laureeeengarcia'. I went through to the organisation and removed her repository, and whenever she now attempts to recreate a repository, she receives a message "Your assignment has been created here: #" (where "#" leads to a "#success").

Some other users have been able to register correctly, and unfortunately I haven't been able to identify a root cause why this is problematic for particular users.

Best regards,
Matt

**Comment by johndbritton** [comment]
> I went through to the organisation and removed her repository, and whenever she now attempts to recreate a repository, she receives a message "Your assignment has been created here: #" (where "#" leads to a "#success").

@MattForshaw This is expected behavior, as you have deleted the repository from GitHub there is nothing for the app to link to.

Can you open another issue for this, as it's a separate problem than an improperly named repository.

**Comment by MattForshaw** [comment]
Good afternoon @johndbritton, thank you for the quick reply to this.

As mentioned above; the reason I attempted to remove her repository was because it was intially incorrectly named as "https://github.com/NCL-CloudComputing/csc8110-cloud-computing-2015-16-laureeeengarcia".

This is very much the same issue.

Many thanks,
Matt

**Comment by johndbritton** [comment]
@MattForshaw I missed the part about it being misnamed, but the fact that the link leads to `#success` is unrelated to the repository having been misnamed. That link is wrong because the repository on GitHub doesn't exist anymore. If it hadn't been deleted, it would link to the incorrectly named repository.

#393 Should fix the naming issue, but it will not resolve the broken link issue.
