### ISSUE TITLE
Logo / Branding

### ISSUE THREAD

**Issue by tarebyte** [education/classroom#42]
Right now this is the logo for Classroom

![screen shot 2015-06-23 at 07 55 31](https://cloud.githubusercontent.com/assets/564113/8305439/3d2f4512-197d-11e5-9a0c-6fd4d380219a.png)

I know other GitHub open source projects like https://notifications.githubapp.com/ have a logo with the GitHub mark and the name of the app.

Can we do something similar? Or if not I'm totally open to suggestions.

**Comment by tarebyte** [comment]
As a side note, I used [Primer](http://primercss.io/) to give it the feel of an app that extends from GitHub. I borrowed the basic layout and look from the Primer site as well.

**Comment by johndbritton** [comment]
I think `Classroom` is a great name for the app itself, but we should probably come up with a way to consistently brand it in the interface. I see a few options:

* GitHub Classroom - Standard branding, matches everything else, easy, obvious association with GitHub. Worries me a bit because this is open source and none of our other open source projects are named like that. In this case, it might make sense because we'll have a single hosted instance of the app.

* Classroom for GitHub - Still clear on GitHub association but has less of an endorsement factor.

* Classroom - Simple and totally free from brand issues, but it's not clearly associated with GitHub.

* Something else - Maybe I'm missing an entirely obvious naming choice.

**Comment by jasoncostello** [comment]
@tarebyte @jglovier Here's an svg logo in the style of the typical sub-brand: 
https://www.dropbox.com/s/pqtxxgo9tbiei2e/github-classroom-logo.svg?dl=0

<img width="617" alt="screen shot 2015-08-17 at 1 15 28 pm" src="https://cloud.githubusercontent.com/assets/416727/9315125/2df3c2cc-44e2-11e5-9113-5cbcb54211ed.png">

**Comment by jasoncostello** [comment]
Wait, takebacksies on that logo. If this is going to be an official, supported channel of communication owned by GitHub as a resource for teachers, we could call it **GitHub for Classrooms**. It'd be branded and the context would be clear, as it is in the style of "GitHub and Government".

**Comment by johndbritton** [comment]
@jasoncostello This will be linked from https://education.github.com/guide, and will be a supported / recommended tool.

Would love your opinion on what domain we should host this on. The current plan is "GitHub Classroom" and `githubclassroom.com` but that's totally flexible depending on what you all think.

**Comment by johndbritton** [comment]
What do folks think about `Classroom for GitHub` rather than `GitHub for Classrooms`?

My logic is that this app is not __GitHub__, it's an app for GitHub to help you manage your GitHub organization.

**Comment by cameronmcefee** [comment]
@johndbritton that's even better in my book

**Comment by jasonlong** [comment]
That works for me. I'll update the logo.

**Comment by jasonlong** [comment]
Closing this for now. Please to be reopening if need be.

![screen shot 2015-08-20 at 10 07 10 am](https://cloud.githubusercontent.com/assets/6104/9385345/f82a0a54-4723-11e5-9f1d-0333d282a3d9.png)

**Comment by johndbritton** [comment]
:clap::start:
