### ISSUE TITLE
User friendly 404 page

### ISSUE THREAD

**Issue by johndbritton** [education/classroom#432]
The 404 page is still the Heroku default, which isn't super helpful for folks. Let's add some custom 404 pages. Specifically, we might consider a custom page for invalid invitation links that says the link is invalid and to contact the organization owner. For other pages, a generic 404 probably makes sense.

**Comment by OrthoDex** [comment]
Hi!
I am currently working on this, and the page renders when I visit /404, but I think we also want it to render when we visit 'assignment-invitations/some-invalid-link'. But this gives me a RecordNotFound error. Should I put a rescue_from clause for it? I don't think that would be the best possible option since it may be caused because of any other reason.

**Comment by tarebyte** [comment]
@OrthoDex I think that would be fine, rescuing `RecordNotFound` and rendering the `404` page should work.

**Comment by OrthoDex** [comment]
@tarebyte I am writing tests for the 404 handling, and I am stuck at trying to get past the authenticate_user! method, since it runs before any action. I have put the test in integration and it says [here](http://stackoverflow.com/questions/5787409/stubbing-authentication-in-request-spec) that the session method is not available to a request spec. Is their any way to get around this? I was thinking of stubbing the current_user method. 
From the link, I thought of creating a helper method but I am a little confused as to how to go about creating such a login helper method.

**Comment by johndbritton** [comment]
@OrthoDex If you make a pull request with your current code we can give you some feedback.

**Comment by OrthoDex** [comment]
@johndbritton  @tarebyte I made a pull request at #510, looking forward to your feedback :)

**Comment by OrthoDex** [comment]
@johndbritton @tarebyte I rewrote the code and opened a new pull request at #596. Sorry for the delay and looking forward to your feedback!

**Comment by BelieveC** [comment]
I would like to work on this!

**Comment by tarebyte** [comment]
Go for it @BelieveC
