### ISSUE TITLE
[Question] Why rails server and not puma in dev?

### ISSUE THREAD

**Issue by allaire** [education/classroom#450]
Hey guys,

Starting to take a look at the project and configuring it locally. Is there any reason why you use `bundle exec rails server` in development instead of puma (that looks configured for production)? IMO it would be a good thing to reproduce the production environment as close as possible when running something in production, but at the same time, I might be missing something :)

Really nice work on classroom by the way, will start to use this instead of custom scripts :smile:

**Comment by allaire** [comment]
Oh and out of curiosity, does GitHub uses Vagrant in some of their projects to avoid "works on my machine" bugs? Our every machine is provisioned with boxen? If so, how do you make sure everyone is running the right version of let say Postgres?

Thanks!

**Comment by tarebyte** [comment]
Hi @allaire, so puma is installed in development mode, https://github.com/education/classroom/blob/e56ac0487a58dab7e44211053f960a97af66dbe3/Gemfile#L38 so when you run `rails server` we do use puma.

The reason we don't use `foreman` to run a Procfile is because I like using pry while developing and pry doesn't work well with foreman. It's just a personal preference.

Also Boxen is not being maintained anymore by GitHub https://github.com/boxen/boxen/issues/197, we're moving to a setup where everything you need is in the project itself and setting up new dev machines uses https://github.com/mikemcquaid/strap. For versioning things like databases we use https://github.com/caskroom/homebrew-versions.

I should update this project to use that convention, I've been a little busy as I just joined GitHub two weeks ago 😁.

**Comment by allaire** [comment]
Thanks mark for insight !

Congrats on the new job as well :)
