### ISSUE TITLE
won't let me accept an assingment

### ISSUE THREAD

**Issue by mmm2360** [education/classroom#461]
for some reason when I click the accept invitation, I get a forbidden message. This isn't happening for others in my class.

**Comment by tarebyte** [comment]
@mmm2360 are you a student? Do you know what organization you are trying to join with your invitation?

**Comment by mmm2360** [comment]
yes I'm a student, this is what comes up when I try to accept invitation:
![screen shot 2016-02-18 at 8 08 01 pm](https://cloud.githubusercontent.com/assets/14302512/13163484/6f26f5f4-d67b-11e5-9dc0-557479510bfa.png)

**Comment by cyhsutw** [comment]
I was trying to understand how `classroom` works this morning, and I encounter the same issue.

My observation:
The account I used as a teacher somehow revoked the permission of `Classroom for GitHub`. This will cause the studnets not able to accept the assignment.
After logging out and in again with the teacher's account, the issue is then solved (since logging in will ask the account to grant permissions to `Classroom for GitHub`).

However, I'm not sure if it is the root cause.

Maybe a better `flash` message will help the teacher/student understand/resolve the similar issues.

I would love to work on the UI refinements mentioned above.

**Comment by tarebyte** [comment]
@cyhsutw @mmm2360 this is known issue see #445

We should verify that the teacher has the proper token before continuing on with the request.

**Comment by cyhsutw** [comment]
@tarebyte Got it, thanks.
