### ISSUE TITLE
Can't sign up with the organisation MVSE-outreach

### ISSUE THREAD

**Issue by willprice** [education/classroom#503]
I get the error:

> Title is too long (maximum is 60 characters)

Any ideas?

**Comment by johndbritton** [comment]
@willprice Can you give us a bit more context:

* What page is this on?
* What are you trying to do?

**Comment by willprice** [comment]
Apologies @johndbritton on rereading my report it is clearly very lacking in information!

I visit: https://classroom.github.com/classrooms, where I am logged in with my github account, that is associated with one organization *MVSE-Outreach*, when a click on create a new classroom (redirectring to https://classroom.github.com/classrooms/new) I am shown the available organisations I can use to create a classroom, the only one shown is *@MVSE-Outreach* as I would expect, I click on this and I get the error message:
> Title is too long (maximum is 60 characters)
And the URL is redirected to https://classroom.github.com/classrooms

Trying this with devtools open doesn't print any errors to the console.

**Comment by johndbritton** [comment]
@willprice Thanks for the additional information, it looks like this error is being caused because the name of your organization is too long for Classroom:

> University of Bristol - Merchant Venturers School of Engineering Outreach

I've labeled this as a bug for us to fix, but in the meantime updating the [name of your organization](https://github.com/organizations/MVSE-Outreach/settings/profile) should help.

**Comment by dinever** [comment]
Hi John @johndbritton,

I wonder if we should fix this by truncating the name of the organization into 60 characters when it's too long.

**Comment by johndbritton** [comment]
> I wonder if we should fix this by truncating the name of the organization into 60 characters when it's too long.

That's one possible solution, although the URL structure of this app has been giving us troubles in a few places. I think we might be better off doing a bigger project to simplify the structure than just solving this one issue. For example we could move to `id` based urls entirely.

**Comment by jrcpulliam** [comment]
I had this problem, too. I solved it by changing the long-form name of the organization to be less descriptive, as suggested above, but I noticed that the next screen automatically took the name of the organization as the suggested name of the classroom, and I wonder if this is the reason for limiting to 60 characters. If so, maybe it would be simple to use the short-form name of the organization instead, since this already has a character limit well under 60. (Sorry if I'm not using the terminology correctly here, but by 'long-form' name I mean what shows up at the top of the organization page - for me this was "Pulliam Lab, UF Department of Biology and Emerging Pathogens Institute" and is now "Pulliam Lab, UF" - and by 'short-form' name I mean what shows up in the URL - for me this is "PulliamLab-UFL".) It would be nice to be able to keep a more descriptive long-form name!

**Comment by go-bears** [comment]
hi @willprice , I just had a conversation with @tarebyte about this issue b/c I wanted to work on it.  The 60-char limitation is a kind of safeguard for teachers. Git apparently won't make repository if the path to the repo or file names are too long.  I hope this information helps!

**Comment by willprice** [comment]
HI @go-bears that's useful to know! Thanks for the information.
