### ISSUE TITLE
Identical 'Settings' buttons in the same view

### ISSUE THREAD

**Issue by dasilvacontin** [education/classroom#513]
<img width="1036" alt="screenshot 2016-03-23 10 07 15" src="https://cloud.githubusercontent.com/assets/1260830/13980488/2bc4b8a4-f0df-11e5-84b7-a926e63ebaa5.png">

There's two identical `Settings` buttons. I know, I know – if you pay enough attention, they are in different contexts / ui boxes:
- the 'Kipos' classroom header, and
- the ui box owned by the 'test' assignment.

Still, it doesn't feel like a good solution, it's not _awesome_ nor it's straightforward to understand. The fact that the buttons are so apart from their modifying elements doesn't make it any easier.

Renaming the first one's label to `Classroom Settings` helps, but it's just a patch, not a solution.

---

Also, any reason not to add the octicon gear icon?

**Comment by johndbritton** [comment]
> There's two identical Settings buttons. I know, I know – if you pay enough attention, they are in different contexts / ui boxes:

This is a good point. @jasonlong Do you have any suggestions for improvement here?

**Comment by jasonlong** [comment]
How about `Manage classroom` for the classroom button since it has more than settings (e.g. inviting other admins)?

`Assignment settings` for the assignment makes sense to me. Maybe we make that one a link with the gear Octicon to visually differentiate rather than having two very similar green buttons.
