### ISSUE TITLE
Private sandbox repos not adding student as collaborator

### ISSUE THREAD

**Issue by cswiercz** [education/classroom#557]
Using the sandbox approach, *on occasion* when a sandboxed / private repo is created for a student using a template the repo does not assign the student as a collaborator and, therefore, they do not have access.

The organization in question is https://github.com/uwhpsc-2016 and the template used for the assignment is https://github.com/uwhpsc-2016/homework1 .

This usually is the case when I have to log out of classrooms and log back in because...reasons. *Sometimes* the student's repo ends up being created as a result. Sometimes not. And sometimes with incorrect permissions.

**Comment by johndbritton** [comment]
This is a known issue, documented here: https://github.com/education/classroom/issues/445

We're actively working on a solution, but we're limited by the GitHub API. The workaround is to have all of the teachers log out and log back in at https://classroom.github.com.

This is caused by a teacher trying out the invitation flow and giving Classroom a reduced scope authentication token. When that happens, we're no longer able to add students to your repositories for you.
