### ISSUE TITLE
Repository: Name Already Exists on Account

### ISSUE THREAD

**Issue by LepcisMagna** [education/classroom#560]
Similar to #557 (this one is actually my class) and #445, I am receiving an error when attempting to accept a homework invitation.  Initially, the errors were among:
"Cannot retrieve this organizations repo plan, please reauthenticate your token.", and 
"You are forbidden from performing this action on github.com", but now each time the error is as below.

![chrome_2016-04-08_16-10-58](https://cloud.githubusercontent.com/assets/9088658/14399756/c083b9aa-fda4-11e5-8953-625d431a6a1b.png)

**Comment by johndbritton** [comment]
The root cause here seems to be the same as those issues, a bad token for one of the organization owners.

To resolve this issue, get your teacher to delete the existing `homework-LepcisMagna` repository or add you to that repository as a collaborator.

You should also let your teachers know not to try out accepting the assignment using their GitHub account, as it will reduce the scopes we have for them and cause this to happen again in the future for other students.

This is a known issue that is caused by a limitation of the GitHub API and we're working on a permanent solution.

cc/ @tarebyte @ptoomey3
