### ISSUE TITLE
Prevent Student from Aborting Import / Allow Reimporting If Aborted

### ISSUE THREAD

**Issue by jvilk** [education/classroom#563]
_[Originally mentioned in this bug thread](https://github.com/github/mentorships/issues/92#issuecomment-209373795), and reposted here._

I'm using GitHub classroom in a class with 100 students using private repositories. The "importer", which creates the repository for a student, allows the student to cancel the import. When this occurs, we are left with an empty repository in our org account.

If I delete the repository, GitHub classroom will not allow the student to re-import the repository; it links to the deleted repository. To fix the issue, I need to create the repository manually. The manually created repo won't show up in GitHub Classroom, but the student will still be able to complete the assignment.

It would be nice to have an easy way to re-create repos when this happens, or perhaps to "reset" them.

**Comment by cyhsutw** [comment]
Hi @jvilk 

Technically, we can completely avoid the problem (by using Webhooks).

We first ensure the source code is successfully imported then add the students as collaborators.
By this, students will not have `write` access to the repo during the import procedure thus they can't abort it.

Students will get email notifications when they are added as collaborators (at the time, the code is already imported so they can start working on the assignment once they receive the emails).

What do you think about this solution?

/cc @johndbritton

**Comment by johndbritton** [comment]
> We first ensure the source code is successfully imported then add the students as collaborators.

This is clever. After the student accepts the assignment, I'd like for us to show a progress indicator on the page hosted by classroom and then update that page after the import completes and the student is added as a collaborator.

Right now, these steps are wrapped in a transaction that will delete the repository if there's an error since it all happens synchronously. If we split them up, we'll want to verify all the steps completed successfully.

**Comment by jvilk** [comment]
Sounds like it would achieve the desired outcome!
