### ISSUE TITLE
Cannot accept assignments

### ISSUE THREAD

**Issue by sdeibel1** [education/classroom#567]
I cannot accept assignments from my organization. I get a message stating that I am "forbidden from performing this action on github.com".

**Comment by tarebyte** [comment]
@sdeibel1 are you a student or a teacher?

**Comment by sdeibel1** [comment]
I am a student.

**Comment by johndbritton** [comment]
@sdeibel1 Please ask your teacher to have all teachers log out of classroom and log back in. This is caused by one of the teachers trying to test out the system as a student. When that happens the application reduces the scopes of the token and makes it impossible for us to create repositories for the students.

See https://github.com/education/classroom/issues/445 for more details / examples.
