### ISSUE TITLE
Copy team access & branch protection from base repo

### ISSUE THREAD

**Issue by dato** [education/classroom#587]
Hello!

Not sure if this will be part of #572, but it’d be great if the copied repo that’s given to students would include:
1. write/admin access for teams that have write/admin permissions in the base repo
2. branch protections from the base repo

Use case: if you have an organization where not all TAs are Owners, it'd be nice to give write/admin privileges in the base repo to the TA team... and have them automatically added to the student’s repo

Same for protected branches, if you have a "review" branch for PRs. You don't want students pushing there directly.

Thanks for considering!

**Comment by cyhsutw** [comment]
@dato thanks for the feedback and very realistic examples!

In my opinions, these features would be really useful for teachers.

@johndbritton should we can link this as one of the subtasks of #572?

**Comment by johndbritton** [comment]
> write/admin access for teams that have write/admin permissions in the base repo
> branch protections from the base repo

Copying these settings from the source repository would make it impossible to create repositories where those permissions are not included.

> if you have an organization where not all TAs are Owners, it'd be nice to give write/admin privileges in the base repo to the TA team... and have them automatically added to the student’s repo

I understand this use case but I think a better solution would be for Classroom to explicitly manage these kinds of permissions rather than just copying them from the source repo to avoid the problem above.

@dato How important is this feature to you? Can you think of other ways it would be use or more generic solutions?

**Comment by nwoodthorpe** [comment]
Deciding what to copy from the base repo is being discussed in #846

Allowing TAs to have elevated priviledges without being an owner is being discussed in #765
