### ISSUE TITLE
Issue creating a team 

### ISSUE THREAD

**Issue by nilmestremas** [education/classroom#597]
Hello,

Once I've chosen my GitHub team's name from a subject of my university degree, I get an error that says something like "You don't have the permit to acces this repository". What should I do?

Thanks,
Nil

**Comment by johndbritton** [comment]
@nilmestremas This is a known issue. It looks like the organization owner has tested out the platform and accepted an assignment. Since we require fewer permissions from students his token was downgraded.

To solve the issue, please tell your teacher to log out and log back in to Classroom and to not accept an assignment invitation with an organization owner account.

**Comment by johndbritton** [comment]
cc/ https://github.com/education/classroom/issues/445
