### ISSUE TITLE
Group Assignment - Minimum number of members

### ISSUE THREAD

**Issue by drbeco** [education/classroom#603]
Following the same line as #288 this is also a feature request.

Please, consider to add an optional field in the settings during creation for the minumum number of members per team.

If edited, only in the direction to open the range (that is, allowing a lower minimum).

What this setting would do: groups that are not in the range (minimum-maximum) would be **froze** until they grab the number of members or the range change to allow the current number of members.

Also, members should be able to move from one group to another as they wish (or at least if there is another option that the teacher set allowing the move -- this can be another feature request in itself, but it is here because it is just a simple statement on how this could work).

**Comment by johndbritton** [comment]
> What this setting would do: groups that are not in the range (minimum-maximum) would be froze until they grab the number of members or the range change to allow the current number of members.

The way Classroom works, we create the repository for the group when the first member accepts an assignment invitation. There's no real way for us to enforce that a group have a minimum number of people.

Do you have some example use cases where this feature would be helpful? Are there any other teachers using Classroom that want this?

I think this is relatively low priority for us if we decide to do it. I'm not convinced it's needed but we won't rule it out entirely. Let's see if other people request the same.

**Comment by drbeco** [comment]
Hello @johndbritton ,

I can't tell on behalf of other teachers, and I hope more teachers comment.

An example, in my case, would be the recurring situation we have when we tell the whole class that there is a task to be done in group, lets say, group of 5, and they ask, of course:

- Teacher, can we work in pairs?
- No, group of five please.
- But teacher, what if there is not enough students?
- Ok, groups of five or six, just to balance, but preferred of five.
- Teacher, can we have groups of 4?
- No, five or six please.
- Teacher, I don't want to work in group, can I work alone?
- No, minimum 5, maximum 6.
- Err, teacher, what if we had a group of 5 and one drop the course?
- That is ok, finish with four.
- Teacher, can we work in couples?
...

And so on... 

I think you got the idea! :laughing:

**Comment by johndbritton** [comment]
Yeah, definitely understand the request. I think we'll keep this at low priority for now given the feedback we've received on the app. If other folks think this is important, please speak up.

**Comment by drbeco** [comment]
Hey @tarebyte , @tabinks , @cyhsutw , @dinever and @johndbritton , give me some support here! Need you! :smile: 

I rather use the only **minimum** than the maximum! Because if I set only the minimum, and I only invite students in a class that obviously have a limited number of sits, I can with only one number set also the approximated number of groups the class would be divided into!

That is really hand!

For example, a class with 30 students.

* If I set (only) the minimum of 4, and _knowing that they don't like to work together_ :smile: than I'll probalby end up with a bit less than 10 groups. (In my experience, 5 or 6 groups approx., but never 7)
* If I set (only) the maximum, lets say, of 5 students, I'll probably end up with 15 groups of 2 students, or even more if some decided to go solo.
* And of course with this option we would have the nice opportunity to set both, so I could say: minimum 4, maximum 6. That would lead to the options:

Group of 4 | Group of 5 | Group of 6 | Total of Groups
---------------|----------------|--------------- |---------------------
       0         |         0        |        5         | 5 (unlikely)
       3         |         0        |        3         | 6 (unlikely)
       2         |         2        |        2         | 6
       1         |         4        |        1         | 6 
       6         |         0        |        1         | 7 (unlikely)
       0         |         6        |        0         | 6

So, more control to the teacher.

**Comment by dinever** [comment]
Hi @drbeco,

This request is pretty reasonable, but there may be a little difficulty in the implementation. There is a solution that I can come up with which may be an implementation of the feature.

Create the assignment repository only if the team reaches the minimum number of students. For example, if the minimum number of student is set to **4**, the repository will not be created for a team until the 4th student joined. Besides, we'll also have to build an interface on the invitation page to give students the ability to rejoin a team if their team does not meet the minimum member requirement and would like to move to another team.

As you can see, this will be a big change and we currently have something high-priority on our roadmap: #572. However, we're planning to implement a team management interface in #292 soon, which would provide teachers the ability to reorganize the student groups. The team management interface should be able to solve the problem you stated above as teachers will be able to move a student from one group to another. In addition, we're also planning to implement #415, which gives teachers the ability to pre-define a set of teams so that the teacher can make sure all students form into a certain number of teams. For example, you will be able to pre-define 5 teams for the group assignment and students must join one of them to accept the assignment.

Please let me know whether you think the future team management interface and pre-defined teams features can solve the problem above. Thanks! 🙇

**Comment by drbeco** [comment]
Hello @dinever , thanks for commenting.

The bugs you quoted are very interesting. One of them I already read. The others are terrific. I hope `classroom` will keep improving like this.

All of them set, they would definitely make a good _workaround_, but they would not substitute the **minimum** set. With a minimum set, the teacher can let the students self-organizing, and I do my best to keep my time worth; so If I'm not needed to settle small problems, all the better.

The ability to change from one group to another is very important! I believe a table with columns representing the groups that the students can click-drag their names from one to another would be fantastic!

They will certainly love it, because it solves one of the most common problems when they are dividing: who goes with who? The best students sometimes are disputed by the lazy ones (just saying! :smile: ) 

And to be fair, I don't know any tool that do that as easily as a drag/drop.

(Maybe this comment/suggestion above should be in another issue)

Well, I hope the minimum set still stays on the table. :+1:

**Comment by drbeco** [comment]
Hi guys, this is an example that shows the need for a minimum

If I only have a **minimum**, I would set the range for 2-3 for this exercise. But then, because I would like to use classroom, I let them choose and pick the way they want.

Look...

![image](https://cloud.githubusercontent.com/assets/5805111/15983167/0b9bbdfa-2f75-11e6-84f8-43dcd4db912a.png)

**Comment by bjb568** [comment]
It would be incredibly annoying as a student to have my repository frozen before I get other students on my team to drag along as I do all the work regardless. Forcing a minimum number of group members seems like it would just be a needless constraint that impedes students with little benefit to anybody. If this gets implemented, I hope the usability from the student perspective is given a good bit of thought.

**Comment by drbeco** [comment]
Not *forcing*, but an optional setup. Of course all students can talk to each teacher to see if it will or not be used in each project. Once the teacher in agreement with the students set the minimum, there is no other way to give this option some sense except to freeze until it is met. (What good a minimum that can be ignored will do after all?)

If the project doesn't need a minimum, it will be just as right now. If it need, I'm sure the teacher will tell all students that this little annoyance reported is just as like as it occurs in some real world projects, when you need to deal with all kinds of constrains and need to learn to work as a team.

In my humble opinion, github is more important to teach team work than anything else; specially first-years students.

**Comment by bjb568** [comment]
I think it's a lot more important to teach students the reality that their individual work is much more important than group work and successful group work both in school and at work means doing other people's work. Just considering the student UX, software-mandated minimum group sizes and freezes on projects before more names are found to be tacked on seems like an annoyance that serves only to stifle productivity and learning — an annoyance, NB, that I think would be blamed on GitHub software rather than anything else.

Preparing students, especially in IT, for the real world means allowing them to develop individually without artificial constraints that wouldn't exist in a work setting. The paragons of the "bright thinkers of tomorrow" aren't smiling faces that are happy to work with others in software-mandated minimum group sizes, rather, they are analytic problem solvers that work on their own with what they have and involve people when necessary, rather than because of a constraint based on a mislead effort to teach soft skills.

**Comment by HugoLnx** [comment]
Hi! As a student, I agree with bjb568 that would be annoying to be blocked until the group have the minimum.

Maybe a better way to do that would be to the teacher set the amount of students that will make the assignment and the amount of groups teacher want so Classroom can create balanced groups with fixed sizes that students choose which one they want to join. Suppose you have 31 students and you want groups of 5-6, you could set that you want 6 groups. So Classroom would create one group of 6 students and five groups of 5 students, that way you don't have to block students from pushing because you know that every group is bound to be complete.

I made a [quick prototype](https://gist.github.com/HugoLnx/5c08c9f3c775fb410abdd082a9a1617c) to illustrate the idea:

**Teacher's View**
![Teacher's View](http://i.giphy.com/3o6ZtlC6rul10LemL6.gif)

**Student's View**
![Student's View](http://i.giphy.com/l3vRkIgr4uXtlOBzi.gif)

Hope it helps, bye!

**Comment by drbeco** [comment]
The problem with that is that the number of students decay over the semester. Some drop in the first weeks, having started the first assignments, some drop in the middle, completing the initial assignments and maybe starting some others... And you never know, you can't predict, and even if they contact the professors to tell they will drop, that is the kind of management that professors won't have time to do. It is not possible to keep track of that, having multiple classes with dozens of students each.

So, again: it is something to make a teachers life easier. I don't see any problem with that. But, well, it is still a suggestion. I figure you guys would like some "teachers" feedback in this project, right?

**Comment by drbeco** [comment]
Please how are our standing in this feature-request?

I would like to address some of the criticism above.

It is actually an "open" option that would not violate or constrain anything if chosen not to be used (for example, default it to zero if not set, or manually set it to zero if one's wish).

Some students above wrote that that would be annoying to need to wait instead of starting immediately to work. But the way I see, github classroom can be used by a diverse range of teachers teaching a even more diverse pool of courses. It is obviously that if one of the main important content is to teach team work and deal with github conflicts/resolution, there is no point allowing a single student starting without their peers. I can think of many more useful reasons, and of course I can think of many reasons not to use the minimum also, that is why it is **optional** (set it to zero if you don't want to use it).

The implementation could be: to wait until the number of members reach the minimum and only then trigger the creation of the repositories.

Thank you

**Comment by fjorgemota** [comment]
Hey.

I'm working on a class on the Federal University of Santa Catarina where we need to define a maximum and a minimum number of students per groups (we need groups with the maximum of three students and the minimum of two, so it's viable to verify all the submissions).
Another way to see that at least on my case would be a limit for the number of groups that can be created. For example, on my case, as the class have ~30 students, the teacher would be able to limit the number of groups to 12 and the maximum number of students on each group to 3. This way, a number of problems were fixed: Who creates a group can start working immediately;- As there are the limit of 12 groups, the students would need to arrange on groups that will have at least two students (which remember the Pigeonhole principle, I think);- The limit of three students per group would still be valid;

Of course, I still think that a minimum number of students would be great. On this case, a valid idea would be to register submissions only for groups with the minimum number of students specified. So everyone can start working immediately and the teacher would have what he wants.

What do you think? Are these ideas good? I would love to have this issue fixed and an option to set the minimum number of students per group on Github Classroom.

Thanks. And keep the good work! =)

**Comment by mozzadrella** [comment]
@fjorgemota that is a great pedagogical question for the education community: https://education.github.community/

**Comment by fjorgemota** [comment]
I don't understood.

When I asked "what do you think?" I asked on the context of this issue of
the Github Classroom project, where a discussion happened about how to add
this feature and it was asked about feedback of users of the application. I
do not see how asking on a education community would help here, as I don't
have any doubts about the method, just a few suggestions to help on the
development of this feature on github classroom.

Sorry if my first comment was not clear about my intentions here.

Em qua, 28 de fev de 2018 13:38, Vanessa <notifications@github.com>
escreveu:

**Comment by d12** [comment]
Hey @drbeco !

https://github.com/education/classroom/pull/1876 merged earlier this summer which adds an optional maximum number of teams. Combined with a maximum number of students per team, this should solve your problem.

**Comment by drbeco** [comment]
Thank you @d12 .

I understand why you think this solve the issue. 

But not really. The main reason was to not allow the first student to join to make a lot of commits in a group work with others, rendering the others that join late to follow from the given commit history without having a "say" on how the program would work, what frameworks they would chose, etc.

Usually there is a "dominant" student that lead the team, but if the team are not able to catch up, this selfish leadership only hurts.

So, if I state that the commits would be open only when, lets say, 3 students have joined, no matter how eager and fast the first 2 are, they will need to wait another one to join. Meanwhile they can start issues and discussions, wiki pages, etc.

But if you feel like this issue will never be implemented (minimum number allowed), then you may keep it closed.

Thanks a lot for all the efforts, independent of this small issue.
