### ISSUE TITLE
Cannot retrieve this organizations repo plan, please reauthenticate your token.

### ISSUE THREAD

**Issue by akagr** [education/classroom#664]
Hey!

Our students are getting the above error when they are trying to join our classroom using invitation link. Previous mentions of this error in closed issues told us to ask them to sign out and sign in after clicking on the link. That didn't help.

What's interesting is that I'm admin of this organisation and I get the same error when I'm trying to create a new assignment. The Github settings for this organisation doesn't show any obvious problems. Github classroom is approved in 3rd party apps.

Any help in locating the source of this problem would be appreciated.

**Comment by akagr** [comment]
@tarebyte that's right

**Comment by akagr** [comment]
@tarebyte If it helps, I reviewed the organisation's audit log. Looks like there's a repo add action (for the student signing up) followed immediately by a repo delete action. Don't know where that's coming from.

**Comment by peggyfox** [comment]
Hi, has there been any resolution to this issue? I am receiving the "Cannot retrieve this organizations repo plan, please reauthenticate your token." error message when trying to accept an assignment. I also tried logging out and back in. Thanks for your help @tarebyte !

**Comment by mariopineda** [comment]
Everytime my students are trying to accept an assignment they get the following error message (see screen shot). If they click on the accept button again (which the message seems to suggest one should do) they end up with multiple copies of the assignment repository. 

Screenshot of error (top) and an example of multiple copies of the same assignmnt repo caused by clicking on the accept button more than once (bottom).
![githuberrors](https://cloud.githubusercontent.com/assets/178373/19411352/65cc4fd2-92bd-11e6-809b-2129043c6f0b.png)

**Comment by tarebyte** [comment]
@mariopineda it looks like one of the owners of your org was removed and so we were still trying to use their token.

I've removed that user from your Classroom. Please let me know if you have any other questions.

**Comment by Gruximillian** [comment]
@tarebyte 

Hello, I'm having this issue again for the `Modern Developer Students` class.
I have read this disscussion, and also #464, and #770, and I think that I understood that when the person who creates the assignment is removed from the organization, then this issue arises.

I just got added recently to the organization, and the person who created the assignments is no longer in the organization, so our students have this issue when they try to accept the assignments.
Since I see that this is not the first time happening to us, and it might happen again if I for example crate the assignments and then leave the organization, I think that the founder of the organization will be the safest choice for the person who creates the assignments. Am I right?

In the previous situations the issue was resolved by changing the name of the assignment (the prefix that's added to the student's repository name), but we would like to have only one prefix, that is, to use the original one, which was 'coursework'.
Can you please help me with this? Thanks!

**Comment by tarebyte** [comment]
> if I for example crate the assignments and then leave the organization, I think that the founder of the organization will be the safest choice for the person who creates the assignments. Am I right?

@Gruximillian while that is correct, the problem with that solution is that the founder would also have to do all of the work in creating the assignments.

For the time being I made you the creator of the assignments so that the assignment isn't broken.

If you'd like to email me about the assignments (tarebyte AT github dot com) I can help you resolve that as well.

Thanks!

**Comment by Gruximillian** [comment]
@tarebyte 
Thank you for the swift reply. Our assignment is just the starting repository structure that the students have to use and maintain. We do not assign any other assignments using the GitHub Classroom, so it is possible that once it is set up, the assignment will stay the same, so far that was the case. But it's fine now, everything is working, students are able to accept the assignments. We will consult whether the founder of the organization will be creator of the assignments or not and if there will be a change I'll contact you.

> If you'd like to email me about the assignments (tarebyte AT github dot com) I can help you resolve that as well.

If by that you mean to change the assignment name, that would be great. I know I can change the students' repository name after they accept the assignment, but it would be nice to have that functional right away.

Thanks!

**Comment by tarebyte** [comment]
> If by that you mean to change the assignment name, that would be great. I know I can change the students' repository name after they accept the assignment, but it would be nice to have that functional right away.

You can actually change the assignment name in Classroom! There is a settings link on the assignment page 😄

**Comment by Gruximillian** [comment]
@tarebyte 
Oh sorry, I forgot to mention that. I tried that couple of times, and I tried just now, but I get this message: `Your assignment repository prefix must be unique `. But there is no such assignment present in the Classroom. I tried to change it to 'coursework', that is the prefix used at the beginning of the Classroom usage.

**Comment by tarebyte** [comment]
Interesting, please email me so we can discuss the actual assignments and I can help get you squared away.

**Comment by Gruximillian** [comment]
@tarebyte 
Thanks, I have emailed you.

**Comment by greensam** [comment]
I'm having with same problem, where an organization owner was removed and now no new assignments or repositories can be created. Is there a work around?

**Comment by tarebyte** [comment]
> I'm having with same problem, where an organization owner was removed and now no new assignments or repositories can be created. Is there a work around?

There isn't a work around right now, there will hopefully be one 🔜 

In the mean time @greensam I've gone ahead and removed the users that don't belong in your Classroom, and updated the creators so that it is your account. So you should be all squared away for the time being.

**Comment by dogfishbar** [comment]
Hello. I am having the same problems with organization BC-CSCI1102. I do not understand from the above discussion what I can do to fix it.
I created the organization a few years ago (I think) and I am the only person creating assignments. I don't remember the exact sequence of problems but we were getting duplicate repos for some students but not for others and token authentication problems (again, for some students but not others) so I deleted a few students then re-invited them.
I don't know if this is related, but some students who were members of organizations for earlier courses, have been added as Owners of BC-CSCI1102 (because they are TAs.)
Can you give me an idea what to do here?
Thank you,
Bob Muller

**Comment by Kadaaran** [comment]
Hi @dogfishbar ,
Thank you for reporting this issue
Did you change the organization's owner recently (for example one of the organization owners left)? 🤔

**Comment by dogfishbar** [comment]
That's possible. I teach the course regularly, my TAs come and go. One present TA, sc8ing, is an Owner of this org but a Member of a different org (BC-CSCI3366, which is working fine). So I'm not 100% sure that ownership changed but I do think it did.

**Comment by Kadaaran** [comment]
@dogfishbar We removed the old owner, you should be okay now. Tell me if it's not the case and if I can help you with anything.

**Comment by dogfishbar** [comment]
Thank you! Just for my information, that old owner's name wasn't visible to
me, right? Can you tell me who it was?
Thanks again!
Bob

**Comment by leskat47** [comment]
Hi. I am having this problem as well, not only for students, but I am not able to make changes (like creating assignments) either. I did make some changes to staff last week, but I should still be an owner. Anything I do gives me the error: Cannot retrieve this organizations repo plan, please reauthenticate your token.
Help?

**Comment by Kadaaran** [comment]
Hi @leskat47 👋 We removed the owners on Classroom that are not owners on GitHub so you should be good for now ! We have an ongoing PR that should fix this issue for once and for all. 

Thank you for your patience !

**Comment by leskat47** [comment]
Thank you, @Kadaaran!!

**Comment by d12** [comment]
Closing, looks like this one is solved.
