### ISSUE TITLE
Adding Other Administrators - 404

### ISSUE THREAD

**Issue by hollenberry** [education/classroom#688]
Hey @tarebyte ! 

For every organization affiliated with GitHub Classroom, I reach a 404 after following the link in option 1 of "Add New Collaborators", found here:

<img width="1920" alt="screen shot 2016-08-11 at 4 06 46 pm" src="https://cloud.githubusercontent.com/assets/13326548/17607886/a316aae4-5fdd-11e6-8419-e56b4c355942.png">

It takes us to here:

<img width="1920" alt="screen shot 2016-08-11 at 4 07 19 pm" src="https://cloud.githubusercontent.com/assets/13326548/17607897/b6a2bcc4-5fdd-11e6-810f-d36d9fd8e7c0.png">

I was able to reproduce this with every organization that GitHub Teacher uses (3). 

Of those 3 organizations, my personal account shares ownership on the one that I'm using for demo purposes. I also hit a 404 when I attempt access logged in to this account.

**Comment by tarebyte** [comment]
This is broken due to the fact that we changed the url scheme on dotcom for inviting users to organizations.

![screen shot 2016-08-11 at 20 53 01](https://cloud.githubusercontent.com/assets/564113/17609953/843727c8-6007-11e6-8681-6b53e63411fb.png)

If / when the API comes out for this, we'll look at this again. For the mean time I'll patch it.
