### ISSUE TITLE
"Assignment failed to be created"

### ISSUE THREAD

**Issue by kohler** [education/classroom#770]
Thanks for creating this system. In our class (organization `cs61`), students are having trouble with a new assignment. On accepting our classroom link:

**Redacted for privacy purposes** - tarebyte

our students see “Assignment failed to be created”, or another error message, “Cannot retrieve this organizations repo plan, please reauthenticate your token.” Any help possible?

**Comment by tarebyte** [comment]
@kohler without getting in to `@mention` user name specifics (email me tarebyte AT github DOT com if you'd like to know more) you removed an owner from your organization who happened to create the assignment your students are trying to access.

Since their token is not longer valid it was causing an error when accepting the assignment.

I've moved over all of the assignments so that they use your token instead.

**Comment by tarebyte** [comment]
@kohler I've just checked and it seems to be working now, please let me know if I can be of anymore help.

Thanks!

**Comment by kohler** [comment]
Great, thanks so much for awesome fast service!!! Could I have figured this out from the UI?

**Comment by tarebyte** [comment]
Unfortunately no, being able to remove admins from your Classroom is one of the many features I need to open an issue for 🙁

**Comment by jayvdb** [comment]
I also hit this bug today when I temporarily gave @yukiisbored Owner rights to work around #765 . The created assignments could not be used after I revoked his Owner rights.
