### ISSUE TITLE
GraphQL support

### ISSUE THREAD

**Issue by tarebyte** [education/classroom#875]
There are a lot of places (particularly when loading resources) where we can use the new [GitHub v4 API](https://developer.github.com/v4/) to make this less resource intensive.

## Example
One of the big use cases I'm thinking of is when we load assignment and group assignment repositories on the assignment pages.

Instead of loading every repo and every owner with their own HTTP request we could shape a page into one query and just handle the information when we get it back.

Just doing back of the napkin sketches this would take some time to implement so I don't think it should be the highest priority right now, but I'd like to at least discuss it.

Thoughts?

/cc @nwoodthorpe @johndbritton @wilfriedE

**Comment by johndbritton** [comment]
How would this work with caching? Would we be able to cache a whole page request and only run it again if something has changed? Is this guaranteed to be an improvement given the caching we're doing currently?

**Comment by nwoodthorpe** [comment]
So the hurdle in implementing this is that all of our API requests are spread across a bunch of different models and partials. With the current setup, it's impossible to pool them all into one GraphQL query.

Looking at this view:
<img width="1077" alt="screen shot 2017-06-19 at 8 28 48 am" src="https://user-images.githubusercontent.com/4149056/27292806-59cf519c-54c9-11e7-8ff5-51876fa37d6c.png">

Rendering this page goes a little something like this:
<img width="781" alt="screen shot 2017-06-19 at 9 22 50 am" src="https://user-images.githubusercontent.com/4149056/27295202-e227ccb6-54d0-11e7-9024-8e9af042caf4.png">

A group of 3 arrows represents a has-many. E.g. GroupAssignment Show renders multiple GroupAssignmentRepo Show's.

In a situation with 300 students and 100 group assignment repos (Not abnormal for a college class), we see we'd be making around 1 + (3 * 300) + (5 * 100) =   1401 API requests just to view the data for this assignment.

I have a few solutions in mind, I'm going to do a bit more 🤔, I'll post some thoughts here later

**Comment by nwoodthorpe** [comment]
The current model of having GitHubResources where we ask for a resource and it returns us the data won't work with GraphQL at all.

Instead of a model where we models are queried from view partials, we could instead have some sort of `GitHubGraphQLPreparer` object that we instantiate either from the controller or in a view model. We tell it what fields we need, then tell it to fetch, and it generates a GraphQL query and fetches. Then, instead of querying the models from view partials, we query the result of this GraphQL object, which has already fetched all the information we need.

This solution moves all of our API stuff to the backend, but that isn't really an issue when we're only making one API request.

@tarebyte See any issues with this solution? I'm gonna try to come up with some other solutions as well, but this is my first thought.

**Comment by nwoodthorpe** [comment]
Some Profiling:

`/classrooms`: 
Number of classrooms: 2
**API requests made: 3**
```
Octokit GET Request: user/4149056
Octokit GET Request: organizations/29413555
Octokit GET Request: organizations/29438895
```

---

`/classrooms/:classroom_slug:`
Number of assignments: 5
**API requests made: 2**
```
Octokit GET Request: organizations/29413555
Octokit GET Request: user/4149056
```

---

`/classrooms/:classroom_slug:/assignments/:assignment_slug:/`
Number of repos: 5
**API requests made: 42**
```
Octokit GET Request: organizations/29438895
Octokit GET Request: user/4149056
Octokit GET Request: repositories/94806530
Octokit GET Request: repositories/94358824
Octokit GET Request: repositories/94358728
Octokit GET Request: repositories/94806552
Octokit GET Request: repositories/94806605
Octokit GET Request: repositories/94806530
Octokit GET Request: repositories/94806552
Octokit GET Request: repositories/94806605
Octokit GET Request: repositories/94358824
Octokit GET Request: repositories/94358728
Octokit GET Request: user/24702586
Octokit GET Request: user/25543096
Octokit GET Request: user/28878376
Octokit GET Request: user/4149056
Octokit GET Request: user/24723247
Octokit GET Request: user/24702586
Octokit GET Request: user/25543096
Octokit GET Request: user/28878376
Octokit GET Request: repositories/94806552
Octokit GET Request: user/24723247
Octokit GET Request: repositories/94806605
Octokit GET Request: repositories/94358824
Octokit GET Request: user/4149056
Octokit GET Request: user/24702586
Octokit GET Request: repositories/94806530
Octokit GET Request: user/25543096
Octokit GET Request: repositories/94358728
Octokit GET Request: user/28878376
Octokit GET Request: repositories/94806552
Octokit GET Request: repositories/94806605
Octokit GET Request: user/4149056
Octokit GET Request: repositories/94358824
Octokit GET Request: user/24723247
Octokit GET Request: user/24702586
Octokit GET Request: user/25543096
Octokit GET Request: repositories/94358728
Octokit GET Request: repositories/94806530
Octokit GET Request: user/28878376
Octokit GET Request: user/4149056
Octokit GET Request: user/24723247
```

---

`/classrooms/:classroom_slug:/group_assignments/:group_assignment_slug:/`
Number of team: 2
Number of students: 5
**API requests made: 35**
```
Octokit GET Request: organizations/29438895
Octokit GET Request: user/4149056
Octokit GET Request: repositories/94806046
Octokit GET Request: repositories/94806160
Octokit GET Request: repositories/94806046
Octokit GET Request: teams/2393779
Octokit GET Request: repositories/94806160
Octokit GET Request: teams/2393779
Octokit GET Request: teams/2393782
Octokit GET Request: organizations/29438895
Octokit GET Request: teams/2393782
Octokit GET Request: repositories/94806046
Octokit GET Request: organizations/29438895
Octokit GET Request: teams/2393779
Octokit GET Request: repositories/94806160
Octokit GET Request: user/25543096
Octokit GET Request: teams/2393782
Octokit GET Request: repositories/94806046
Octokit GET Request: user/24723247
Octokit GET Request: repositories/94806160
Octokit GET Request: teams/2393779
Octokit GET Request: teams/2393782
Octokit GET Request: user/28878376
Octokit GET Request: user/24702586
Octokit GET Request: repositories/94806046
Octokit GET Request: repositories/94806160
Octokit GET Request: teams/2393779
Octokit GET Request: teams/2393782
Octokit GET Request: repositories/94806046
Octokit GET Request: user/4149056
Octokit GET Request: teams/2393779
Octokit GET Request: repositories/94806160
Octokit GET Request: teams/2393782
Octokit GET Request: repositories/94806160
Octokit GET Request: teams/2393782
```

**Comment by nwoodthorpe** [comment]
Observations from the profiling above:

- Lots of endpoint duplication. These weren't cached the requests all had different options, asking for different pieces of data.
- The API requests in `/classrooms` grow linearly with the number of classrooms. Not a huge issue.
- The API requests in `/classrooms/:classroom:/` are actually constant, which is awesome.
- Viewing assignments or group assignments spawns TONS of API requests. I only have 5 accounts, and I was already hitting 40 API requests on a single page load. My hypothesis above about a college class hitting 1k API requests in a single page load is 100% possible.

Takeaways from the observations:
- Let's focus on the two pages with absurd amounts of API requests first
- REST + Caching <<<<< GraphQL + No caching ≈ GraphQL with caching.
- POST requests aren't a big deal, lets handle GET requests first since those are the ones that prevent fast page loading.
