### ISSUE TITLE
Allow "Account Creation" by teachers using student identifiers

### ISSUE THREAD

**Issue by nwoodthorpe** [education/classroom#877]
Just moving some stuff from elsewhere here so we can discuss and so it doesn't get buried.

@johndbritton had the idea of solving the "I want to setup accounts for my students" problem that a bunch of teachers are having by allowing the teacher to upload a list of student identifiers (perhaps student ID?) when they create the classroom. Then, when a student goes to accept an assignment (or possibly even before this), we ask them for their identifier. This creates a link between their GitHub and their personal identity, another thing teachers have been asking for.

If the student doesn't already have a GitHub account, we can guide them through the process and then link their new account with the classroom.

This would also help with access control problems, since we can only allow students to accept an assignment / join the classroom if they have an identifier that's on the list.

Since this verifies the student is a student, we could also set them up with the student developer pack without any work on their end.

Also tagging @sanicki @joenash since they were part of the discussion.

**Comment by obcode** [comment]
Great! Two ideas that would be useful, at least for me:

1. Downloadable (JSON or YAML) file containing the mappings from student identifiers to GitHub accounts.

2. The possibility to give each student, which accepts the assignment, automatically write access to a (maybe private) repository containing a wiki and stuff like this, we can use together during the course. (I am doing this by hand at the moment)

Just an idea to make it harder to steal one's identity (I don't know if this is possible due to privacy concerns):

- I provide a list of my students email addresses as upload
- the student has to add this email address to his or her GitHub-Account, which will be verified by the normal github process
- if one of the email addresses can be found as verified email address in his or her account the mapping will be stored in Classroom for later downloading and the repository will be created
- if not the user will be rejected from this classroom

**Comment by nwoodthorpe** [comment]
Thanks for the ideas @obcode 

We'll definitely consider your two feature requests. In our current implementation, they don't exist, but they may soon.

We considered the "Have the user verify their email before joining the classroom" idea, but we decided against it. We don't want students to be unable to work on assignments because of technical issues. Instead, we've given teachers full control over setting the GitHub/identifier mappings. They can correct any issues that arise, and can manually link accounts who haven't linked yet.

This is currently staffshipped and will be full shipped soon. Closing!
